# [AI] 通用参数化RISC-V Toolchain文件，支持不同厂商和LLVM/Clang
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_SYSTEM_VERSION 1)

# Skip the link step in compiler feature try_compile checks.
# Without this, CMake reruns compiler detection on every CMakeLists.txt
# change and loses the sysroot-relative C++ include paths, causing
# 'array' not found errors in incremental builds.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)


# 可通过 -DRISCV_TRIPLE=xxx -DRISCV_ROOT_PATH=xxx -DRISCV_MARCH=xxx -DRISCV_MABI=xxx -DRISCV_USE_LLVM=ON 传参
set(RISCV_TRIPLE "riscv64-unknown-linux-gnu" CACHE STRING "GNU compiler triple")
set(RISCV_ROOT_PATH "" CACHE PATH "root path to riscv toolchain")
set(RISCV_MARCH "rv64gcv_zfh_zba_zicbop" CACHE STRING "RISC-V ISA extensions")
set(RISCV_MABI "lp64d" CACHE STRING "RISC-V ABI")
set(RISCV_USE_LLVM OFF CACHE BOOL "Use LLVM/Clang toolchain if ON, otherwise use GCC")
set(RISCV_SYSROOT "" CACHE PATH "Override sysroot path (defaults to <root>/sysroot or gcc -print-sysroot)")
set(RISCV_LIB_PATH "" CACHE PATH "Directory containing crtbeginS.o/libgcc (defaults to gcc -print-libgcc-file-name parent)")
set(RISCV_ATOMIC_LIB_PATH "" CACHE PATH "Directory containing libatomic (defaults to gcc -print-file-name=libatomic.so parent)")
set(RISCV_NIX_LIBC "" CACHE PATH "Nix glibc root resolved from gcc wrapper")
set(RISCV_NIX_LIBC_DEV "" CACHE PATH "Nix glibc dev root resolved from gcc wrapper")
set(RISCV_STDCXX_LIB_PATH "" CACHE PATH "Directory containing libstdc++ for the target toolchain")

if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(riscv)")
    message(STATUS "HOST SYSTEM ${CMAKE_HOST_SYSTEM_PROCESSOR}")
else()

    # 只在第一次include时强校验，try_compile等阶段丢失变量仅警告
    if (NOT DEFINED CMAKE_TOOLCHAIN_FILE_IS_INCLUDED)
        set(CMAKE_TOOLCHAIN_FILE_IS_INCLUDED TRUE)
        if (NOT RISCV_ROOT_PATH)
            if (DEFINED ENV{RISCV_ROOT_PATH})
                file(TO_CMAKE_PATH $ENV{RISCV_ROOT_PATH} RISCV_ROOT_PATH)
            elseif (DEFINED CMAKE_TRY_COMPILE)
                message(WARNING "[riscv64-toolchain] RISCV_ROOT_PATH missing during try_compile, falling back to empty path.")
            else()
                message(FATAL_ERROR "RISCV_ROOT_PATH env or -DRISCV_ROOT_PATH must be defined")
            endif()
        endif()
        if (RISCV_ROOT_PATH)
            set(ENV{RISCV_ROOT_PATH} "${RISCV_ROOT_PATH}")
        endif()
    else()
        if (NOT RISCV_ROOT_PATH)
            if (DEFINED ENV{RISCV_ROOT_PATH})
                file(TO_CMAKE_PATH $ENV{RISCV_ROOT_PATH} RISCV_ROOT_PATH)
            elseif (DEFINED CMAKE_TRY_COMPILE)
                message(WARNING "[riscv64-toolchain] RISCV_ROOT_PATH missing during try_compile, falling back to empty path.")
            else()
                message(WARNING "[riscv64-toolchain] RISCV_ROOT_PATH is not set in sub-CMake, may cause build issues.")
            endif()
        endif()
        if (RISCV_ROOT_PATH)
            set(ENV{RISCV_ROOT_PATH} "${RISCV_ROOT_PATH}")
        endif()
    endif()

    # 如果环境变量已有记录（例如父配置阶段设置），优先取出
    if (NOT RISCV_SYSROOT AND DEFINED ENV{RISCV_SYSROOT})
        file(TO_CMAKE_PATH $ENV{RISCV_SYSROOT} RISCV_SYSROOT)
    endif()

    # 尝试定位GNU交叉编译器，供后续sysroot/lib路径推导
    if (NOT RISCV_GNU_CC)
        set(_RISCV_TRIPLE_CANDIDATES ${RISCV_TRIPLE})
        if (RISCV_TRIPLE MATCHES "unknown-")
            string(REPLACE "unknown-" "" _RISCV_TRIPLE_NO_UNKNOWN ${RISCV_TRIPLE})
            list(APPEND _RISCV_TRIPLE_CANDIDATES ${_RISCV_TRIPLE_NO_UNKNOWN})
        endif()
        list(APPEND _RISCV_TRIPLE_CANDIDATES "riscv64-linux-gnu")
        foreach(_cand IN LISTS _RISCV_TRIPLE_CANDIDATES)
            find_program(RISCV_GNU_CC ${_cand}-gcc HINTS ${RISCV_ROOT_PATH}/bin)
            if (RISCV_GNU_CC)
                set(RISCV_GNU_TRIPLE ${_cand})
                get_filename_component(RISCV_GNU_BIN_DIR "${RISCV_GNU_CC}" DIRECTORY)
                get_filename_component(RISCV_GNU_ROOT "${RISCV_GNU_BIN_DIR}" DIRECTORY)
                set(ENV{RISCV_GNU_ROOT} "${RISCV_GNU_ROOT}")
                if (EXISTS "${RISCV_GNU_ROOT}/nix-support/orig-libc")
                    file(STRINGS "${RISCV_GNU_ROOT}/nix-support/orig-libc" RISCV_NIX_LIBC LIMIT_COUNT 1)
                endif()
                if (EXISTS "${RISCV_GNU_ROOT}/nix-support/orig-libc-dev")
                    file(STRINGS "${RISCV_GNU_ROOT}/nix-support/orig-libc-dev" RISCV_NIX_LIBC_DEV LIMIT_COUNT 1)
                endif()
                break()
            endif()
        endforeach()
    endif()

    # On reconfigure RISCV_GNU_CC is already cached but RISCV_GNU_ROOT was
    # never stored in the cache — re-derive it from the cached path so that
    # --gcc-toolchain and C++ header -isystem flags are always present.
    if (RISCV_GNU_CC AND NOT RISCV_GNU_ROOT)
        get_filename_component(_riscv_gnu_bin "${RISCV_GNU_CC}" DIRECTORY)
        get_filename_component(RISCV_GNU_ROOT "${_riscv_gnu_bin}" DIRECTORY)
        if (NOT RISCV_GNU_TRIPLE)
            get_filename_component(_riscv_gcc_name "${RISCV_GNU_CC}" NAME_WE)
            string(REGEX REPLACE "-gcc$" "" RISCV_GNU_TRIPLE "${_riscv_gcc_name}")
        endif()
    endif()

    # 推导sysroot：优先显式指定，其次<root>/sysroot，再尝试${RISCV_TRIPLE}-gcc -print-sysroot
    if (NOT RISCV_SYSROOT)
        if (RISCV_ROOT_PATH AND EXISTS "${RISCV_ROOT_PATH}/sysroot")
            set(RISCV_SYSROOT "${RISCV_ROOT_PATH}/sysroot")
        else()
            if (RISCV_GNU_CC)
                execute_process(
                    COMMAND ${RISCV_GNU_CC} -print-sysroot
                    OUTPUT_VARIABLE RISCV_GNU_SYSROOT
                    OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET)
                if (RISCV_GNU_SYSROOT AND EXISTS "${RISCV_GNU_SYSROOT}")
                    set(RISCV_SYSROOT "${RISCV_GNU_SYSROOT}")
                endif()
            endif()
        endif()
    endif()

    if (NOT RISCV_SYSROOT)
        if (DEFINED CMAKE_TRY_COMPILE)
            message(WARNING "[riscv64-toolchain] RISCV_SYSROOT is empty during try_compile, toolchain may fail to link.")
        else()
            message(FATAL_ERROR "RISCV_SYSROOT could not be determined; pass -DRISCV_SYSROOT=<path> or ensure ${RISCV_TRIPLE}-gcc -print-sysroot works")
        endif()
    endif()

    if (RISCV_SYSROOT)
        set(ENV{RISCV_SYSROOT} "${RISCV_SYSROOT}")
    endif()

    # 推导lib路径（crtbeginS.o、libgcc等）
    if (NOT RISCV_LIB_PATH)
        if (DEFINED ENV{RISCV_LIB_PATH})
            file(TO_CMAKE_PATH $ENV{RISCV_LIB_PATH} RISCV_LIB_PATH)
        elseif (RISCV_GNU_CC)
            execute_process(
                COMMAND ${RISCV_GNU_CC} -print-libgcc-file-name
                OUTPUT_VARIABLE RISCV_LIBGCC_FILE
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET)
            if (RISCV_LIBGCC_FILE)
                get_filename_component(RISCV_LIB_PATH "${RISCV_LIBGCC_FILE}" DIRECTORY)
            endif()
        endif()
    endif()

    if (RISCV_LIB_PATH)
        set(ENV{RISCV_LIB_PATH} "${RISCV_LIB_PATH}")
    endif()

    if (NOT RISCV_ATOMIC_LIB_PATH)
        if (DEFINED ENV{RISCV_ATOMIC_LIB_PATH})
            file(TO_CMAKE_PATH $ENV{RISCV_ATOMIC_LIB_PATH} RISCV_ATOMIC_LIB_PATH)
        elseif (RISCV_GNU_CC)
            foreach(_RISCV_ATOMIC_NAME libatomic.so libatomic.so.1)
                execute_process(
                    COMMAND ${RISCV_GNU_CC} -print-file-name=${_RISCV_ATOMIC_NAME}
                    OUTPUT_VARIABLE RISCV_ATOMIC_FILE
                    OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET)
                if (RISCV_ATOMIC_FILE AND IS_ABSOLUTE "${RISCV_ATOMIC_FILE}" AND EXISTS "${RISCV_ATOMIC_FILE}")
                    get_filename_component(RISCV_ATOMIC_LIB_PATH "${RISCV_ATOMIC_FILE}" DIRECTORY)
                    break()
                endif()
            endforeach()
        endif()
    endif()

    if (RISCV_ATOMIC_LIB_PATH)
        set(ENV{RISCV_ATOMIC_LIB_PATH} "${RISCV_ATOMIC_LIB_PATH}")
    endif()

    if (NOT RISCV_STDCXX_LIB_PATH AND RISCV_GNU_CC)
        set(RISCV_GNU_CXX_CMD "")
        if (RISCV_GNU_TRIPLE)
            find_program(RISCV_GNU_CXX_CMD ${RISCV_GNU_TRIPLE}-g++ HINTS ${RISCV_GNU_ROOT}/bin)
        endif()
        if (NOT RISCV_GNU_CXX_CMD AND RISCV_GNU_ROOT)
            foreach(_RISCV_GNU_CXX_NAME riscv64-unknown-linux-gnu-g++ riscv64-linux-gnu-g++)
                find_program(RISCV_GNU_CXX_CMD ${_RISCV_GNU_CXX_NAME} HINTS ${RISCV_GNU_ROOT}/bin)
                if (RISCV_GNU_CXX_CMD)
                    break()
                endif()
            endforeach()
        endif()
        foreach(_RISCV_STDCXX_NAME libstdc++.so libstdc++.a)
            if (RISCV_GNU_CXX_CMD)
                execute_process(
                    COMMAND ${RISCV_GNU_CXX_CMD} -print-file-name=${_RISCV_STDCXX_NAME}
                    OUTPUT_VARIABLE RISCV_STDCXX_FILE
                    OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET)
            endif()
            if (RISCV_STDCXX_FILE AND IS_ABSOLUTE "${RISCV_STDCXX_FILE}" AND EXISTS "${RISCV_STDCXX_FILE}")
                get_filename_component(RISCV_STDCXX_LIB_PATH "${RISCV_STDCXX_FILE}" DIRECTORY)
                break()
            endif()
        endforeach()
    endif()

    if (RISCV_STDCXX_LIB_PATH)
        set(ENV{RISCV_STDCXX_LIB_PATH} "${RISCV_STDCXX_LIB_PATH}")
    endif()

    # 支持GCC和Clang自动切换
    if (RISCV_USE_LLVM)
        set(CMAKE_C_COMPILER   ${RISCV_ROOT_PATH}/bin/clang)
        set(CMAKE_CXX_COMPILER ${RISCV_ROOT_PATH}/bin/clang++)
        set(CMAKE_STRIP        ${RISCV_ROOT_PATH}/bin/llvm-strip)
                if (RISCV_NIX_LIBC AND EXISTS "${RISCV_NIX_LIBC}")
            set(RISCV_SYSROOT_FLAG "")
            set(CMAKE_SYSROOT "")
            set(CMAKE_SYSROOT_COMPILE "")
            set(CMAKE_SYSROOT_LINK "")
        else()
            set(RISCV_SYSROOT_FLAG "--sysroot=${RISCV_SYSROOT}")
        endif()
        set(RISCV_TARGET_FLAG  "--target=${RISCV_TRIPLE}")
        set(CMAKE_C_COMPILER_TARGET   ${RISCV_TRIPLE})
        set(CMAKE_CXX_COMPILER_TARGET ${RISCV_TRIPLE})
        set(CMAKE_C_FLAGS_INIT   "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} -march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
        set(CMAKE_CXX_FLAGS_INIT "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} -march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
    else()
        set(CMAKE_C_COMPILER   ${RISCV_ROOT_PATH}/bin/${RISCV_TRIPLE}-gcc)
        set(CMAKE_CXX_COMPILER ${RISCV_ROOT_PATH}/bin/${RISCV_TRIPLE}-g++)
        set(CMAKE_STRIP        ${RISCV_ROOT_PATH}/bin/${RISCV_TRIPLE}-strip)
        set(CMAKE_FIND_ROOT_PATH "${RISCV_SYSROOT}")
        set(CMAKE_SYSROOT        "${RISCV_SYSROOT}")
    endif()
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# 支持自定义march/mabi，兼容C/C++
if (RISCV_USE_LLVM)
    set(RISCV_LLVM_COMMON_FLAGS "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} -march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
    if (RISCV_GNU_ROOT)
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} --gcc-toolchain=${RISCV_GNU_ROOT}")
        if (EXISTS "${RISCV_GNU_ROOT}/include/c++")
            file(GLOB _RISCV_CPP_VERSIONS RELATIVE "${RISCV_GNU_ROOT}/include/c++" "${RISCV_GNU_ROOT}/include/c++/*")
            list(FILTER _RISCV_CPP_VERSIONS INCLUDE REGEX "^[0-9].*")
            list(SORT _RISCV_CPP_VERSIONS)
            list(REVERSE _RISCV_CPP_VERSIONS)
            if (_RISCV_CPP_VERSIONS)
                list(GET _RISCV_CPP_VERSIONS 0 _RISCV_CPP_VER)
            endif()
            if (_RISCV_CPP_VER)
                set(RISCV_GNU_CXX_INCLUDE "${RISCV_GNU_ROOT}/include/c++/${_RISCV_CPP_VER}")
                set(RISCV_GNU_CXX_INCLUDE_TARGET "${RISCV_GNU_CXX_INCLUDE}/${RISCV_GNU_TRIPLE}")
            endif()
        endif()
    endif()
    if (RISCV_LIB_PATH)
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} -B${RISCV_LIB_PATH}")
    endif()
    if (RISCV_GNU_CXX_INCLUDE)
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} -isystem${RISCV_GNU_CXX_INCLUDE}")
    endif()
    if (RISCV_GNU_CXX_INCLUDE_TARGET AND EXISTS "${RISCV_GNU_CXX_INCLUDE_TARGET}")
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} -isystem${RISCV_GNU_CXX_INCLUDE_TARGET}")
    endif()
    if (RISCV_NIX_LIBC_DEV AND EXISTS "${RISCV_NIX_LIBC_DEV}/include")
        set(RISCV_LLVM_COMMON_FLAGS "${RISCV_LLVM_COMMON_FLAGS} -isystem${RISCV_NIX_LIBC_DEV}/include")
        include_directories(SYSTEM "${RISCV_NIX_LIBC_DEV}/include")
    endif()
    if (RISCV_SYSROOT AND EXISTS "${RISCV_SYSROOT}/include")
        include_directories(SYSTEM "${RISCV_SYSROOT}/include")
    endif()
    if (RISCV_GNU_CXX_INCLUDE)
        include_directories(SYSTEM "${RISCV_GNU_CXX_INCLUDE}")
        if (EXISTS "${RISCV_GNU_CXX_INCLUDE}/${RISCV_GNU_TRIPLE}")
            include_directories(SYSTEM "${RISCV_GNU_CXX_INCLUDE}/${RISCV_GNU_TRIPLE}")
        endif()
    endif()
    set(CMAKE_C_FLAGS   "${RISCV_LLVM_COMMON_FLAGS} ${CMAKE_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${RISCV_LLVM_COMMON_FLAGS} ${CMAKE_CXX_FLAGS}")
    find_program(RISCV_LLD ld.lld HINTS ${RISCV_ROOT_PATH}/bin NO_DEFAULT_PATH)
    if (RISCV_LLD)
        set(RISCV_LLD_FLAG "-fuse-ld=${RISCV_LLD}")
    else()
        set(RISCV_LLD_FLAG "-fuse-ld=lld")
    endif()
    set(RISCV_LLVM_LINK_FLAGS "${RISCV_TARGET_FLAG} ${RISCV_SYSROOT_FLAG} ${RISCV_LLD_FLAG}")
    set(RISCV_LLVM_LINK_DIRS "")
    if (RISCV_LIB_PATH)
        list(APPEND RISCV_LLVM_LINK_DIRS "${RISCV_LIB_PATH}")
    endif()
    if (RISCV_ATOMIC_LIB_PATH)
        list(APPEND RISCV_LLVM_LINK_DIRS "${RISCV_ATOMIC_LIB_PATH}")
    endif()
    if (RISCV_STDCXX_LIB_PATH)
        list(APPEND RISCV_LLVM_LINK_DIRS "${RISCV_STDCXX_LIB_PATH}")
    endif()
    if (RISCV_NIX_LIBC AND EXISTS "${RISCV_NIX_LIBC}/lib")
        list(APPEND RISCV_LLVM_LINK_DIRS "${RISCV_NIX_LIBC}/lib")
    endif()
    if (RISCV_LLVM_LINK_DIRS)
        list(REMOVE_DUPLICATES RISCV_LLVM_LINK_DIRS)
        foreach(_RISCV_LINK_DIR IN LISTS RISCV_LLVM_LINK_DIRS)
            set(RISCV_LLVM_LINK_FLAGS "${RISCV_LLVM_LINK_FLAGS} -L${_RISCV_LINK_DIR} -B${_RISCV_LINK_DIR}")
        endforeach()
    endif()
    
    # Configure linking based on BUILD_SHARED_LIBS
    if (NOT BUILD_SHARED_LIBS)
        # Static linking of libstdc++, libgcc, and OpenMP, but allow dynamic glibc
        # This avoids issues with missing static C++ standard library
        set(CMAKE_EXE_LINKER_FLAGS "${RISCV_LLVM_LINK_FLAGS} ${CMAKE_EXE_LINKER_FLAGS} -static-libstdc++ -static-libgcc -latomic")
        message(STATUS "RISC-V Toolchain: Using static libstdc++/libgcc")
    else()
        # Dynamic linking with static OpenMP
        set(CMAKE_EXE_LINKER_FLAGS "${RISCV_LLVM_LINK_FLAGS} ${CMAKE_EXE_LINKER_FLAGS} -latomic -static-libgcc -static-libstdc++ -Wl,-Bstatic -lomp -Wl,-Bdynamic")
        message(STATUS "RISC-V Toolchain: Using dynamic linking with static OpenMP")
    endif()
    set(CMAKE_SHARED_LINKER_FLAGS "${RISCV_LLVM_LINK_FLAGS} ${CMAKE_SHARED_LINKER_FLAGS}")
else()
    set(CMAKE_C_FLAGS   "-march=${RISCV_MARCH} -mabi=${RISCV_MABI} ${CMAKE_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "-march=${RISCV_MARCH} -mabi=${RISCV_MABI} ${CMAKE_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -latomic")
endif()
